name: Build and upload To-Do List Vue app to S3

on: 
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Build Vue app
      run: |
        cd apps/to-do-list
        npm install
        npm run test
        npm run build

    - name: Configure AWS Credentials
      uses: aws=actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Deploy To-Do-List app to S3 bucket for static hosting
      run: aws s3 sync ./apps/to-do-list/dist/ s3:// snazzy-todo-list --delete